### ISSUE TITLE
general / offtopic question about incompatibility with other libraries...

### ISSUE THREAD

**Issue by moebiussurfing** [Yveaux/LedPattern#2]
First of all, thanks a lot @Yveaux for your library! Is being very helpful for my last project; and other people should know for it.
I am using the lib for a big_start_arcade_ligthing_button for a computer TV station based on Arduino + openFrameworks app connected through usb serial com.

The thing is that sometimes I am stuck with some errors that I can't debug fine (I don't know how).
I use Visual Micro as Arduino IDE in MS Visual Studio (Arduino Mega & Uno + 1 NeoPixel RGB led). 
I can't figure out why sometimes the Arduino hangs and stops working and it falls freezed.

When modifying the led patterns (I think...), sometimes the code backs to work fine. Also just disabling the serial1 (second aux port used to debug) makes the code stop working (?)... I started with the FastLed examples.

I suspect that maybe is related to some incompatibility (timers?, interrupts?, used pins?, to debug on serial on a listener function?...) with the others libraries I am using. But I don't know what I have to check inside the other libs (and also into LedPattern) to disable/debug the problems.

The other libs I am using are this ones:
https://github.com/bakercp/PacketSerial
https://github.com/mathertel/OneButton
https://github.com/TinkerKit/DmxMaster
https://github.com/pfeerick/elapsedMillis

Any idea of how/where to start check around?
Thanks again! I'll post here my progress if I see something helpful...

**Comment by Yveaux** [comment]
@moebiussurfing Great to hear you like the library!
I'm not aware of any incompatibilities with other libraries.
Also, from your message it doesn't become clear how you use it, e.g. which patterns or if update() is called from loop() or timer context.
If you post (the relevant parts of) your sketch I might be able to help.

**Comment by Yveaux** [comment]
Closed due to inactivity
